<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Small</formFactors>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Public Sector: License and Permit Management</label>
    <navType>Console</navType>
    <tabs>standard-home</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-BusinessProfile</tabs>
    <tabs>standard-PublicComplaint</tabs>
    <tabs>standard-BusinessLicenseApplication</tabs>
    <tabs>standard-IndividualApplication</tabs>
    <tabs>standard-RegulatoryCodeViolation</tabs>
    <tabs>standard-ViolationEnforcementAction</tabs>
    <tabs>standard-InspectionApp</tabs>
    <uiType>Lightning</uiType>
    <workspaceConfig>
        <mappings>
            <tab>standard-Account</tab>
        </mappings>
        <mappings>
            <tab>standard-BusinessLicenseApplication</tab>
        </mappings>
        <mappings>
            <tab>standard-BusinessProfile</tab>
        </mappings>
        <mappings>
            <tab>standard-IndividualApplication</tab>
        </mappings>
        <mappings>
            <tab>standard-InspectionApp</tab>
        </mappings>
        <mappings>
            <tab>standard-PublicComplaint</tab>
        </mappings>
        <mappings>
            <tab>standard-RegulatoryCodeViolation</tab>
        </mappings>
        <mappings>
            <tab>standard-ViolationEnforcementAction</tab>
        </mappings>
        <mappings>
            <tab>standard-home</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
